[general]
import = [
    "./themes/gruvbox_dark.toml"
]

[window]
padding = { x = 8, y = 8 }
opacity = 0.90 

[font]
size = 15
normal = { family = "JetBrainsMono Nerd Font", style = "Medium" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }
